# Generated by Django 3.0.5 on 2020-05-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='compplete',
            new_name='complete',
        ),
    ]
